Allow stricter permissions but not looser; Change default permissions to 0400; Correct and improve `unprotected key file' message.
square/certstrap pull request #138
Opened 2022-01-14 03:33 UTC by SBell6hf

This pull request:
* Allow stricter permissions but not looser
* Change default permissions to 0400
* Change `permission denied` => ``unprotected key file `FILENAME': file permissions too open``
It fixes: https://github.com/square/certstrap/issues/51, https://github.com/square/certstrap/issues/136, https://github.com/square/certstrap/issues/137

2022-01-20 18:35 UTC, jdtw approved these changes

2022-01-20 18:43 UTC, jdtw requested changes
Looks like this test is failing: https://github.com/square/certstrap/blob/master/depot/depot_test.go#L124-L126

2022-01-22 10:44 UTC, SBell6hf commented
​

2022-02-08 18:53 UTC, jdtw commented
Thanks so much for filing these issues! I found the tests confusing, so I refactored them and fixed the logic error in https://github.com/square/certstrap/pull/141. After that change, I propose we split this PR into two:

1. Make the error string more descriptive.
2. Change the default file permissions if needed (I left a comment on the issue).

2022-04-02 15:27 UTC, closed without merging